{ pkgs, ... }: {
  programs.firefox = {
    enable = true;
    profiles.thefunbrowser = {
      userChrome =
        "	@-moz-document url(chrome://browser/content/browser.xhtml) {\n	/* tabs on bottom of window */\n	/* requires that you set\n	 * toolkit.legacyUserProfileCustomizations.stylesheets = true\n	 * in about:config\n	 */\n	#main-window body { flex-direction: column-reverse !important; }\n	#navigator-toolbox { flex-direction: column-reverse !important; }\n	#urlbar {\n		top: unset !important;\n		bottom: calc((var(--urlbar-toolbar-height) - var(--urlbar-height)) / 2) !important;\n		box-shadow: none !important;\n		display: flex !important;\n		flex-direction: column !important;\n	}\n	#urlbar-input-container {\n		order: 2;\n	}\n	#urlbar > .urlbarView {\n		order: 1;\n		border-bottom: 1px solid #666;\n	}\n	#urlbar-results {\n		display: flex;\n		flex-direction: column-reverse;\n	}\n	.search-one-offs { display: none !important; }\n	.tab-background { border-top: none !important; }\n	#navigator-toolbox::after { border: none; }\n	#TabsToolbar .tabbrowser-arrowscrollbox,\n	#tabbrowser-tabs, .tab-stack { min-height: 28px !important; }\n	.tabbrowser-tab { font-size: 80%; }\n	.tab-content { padding: 0 5px; }\n	.tab-close-button .toolbarbutton-icon { width: 12px !important; height: 12px !important; }\n	toolbox[inFullscreen=true] { display: none; }\n	/*\n	 * the following makes it so that the on-click panels in the nav-bar\n	 * extend upwards, not downwards. some of them are in the #mainPopupSet\n	 * (hamburger + unified extensions), and the rest are in\n	 * #navigator-toolbox. They all end up with an incorrectly-measured\n	 * max-height (based on the distance to the _bottom_ of the screen), so\n	 * we correct that. The ones in #navigator-toolbox then adjust their\n	 * positioning automatically, so we can just set max-height. The ones\n	 * in #mainPopupSet do _not_, and so we need to give them a\n	 * negative margin-top to offset them *and* a fixed height so their\n	 * bottoms align with the nav-bar. We also calc to ensure they don't\n	 * end up overlapping with the nav-bar itself. The last bit around\n	 * cui-widget-panelview is needed because \"new\"-style panels (those\n	 * using \"unified\" panels) don't get flex by default, which results in\n	 * them being the wrong height.\n	 *\n	 * Oh, yeah, and the popup-notification-panel (like biometrics prompts)\n	 * of course follows different rules again, and needs its own special\n	 * rule.\n	 */\n	#mainPopupSet panel.panel-no-padding { margin-top: calc(-50vh + 40px) !important; }\n	#mainPopupSet .panel-viewstack, #mainPopupSet popupnotification { max-height: 50vh !important; height: 50vh; }\n	#mainPopupSet panel.panel-no-padding.popup-notification-panel { margin-top: calc(-50vh - 35px) !important; }	\n	#navigator-toolbox .panel-viewstack { max-height: 75vh !important; }\n	panelview.cui-widget-panelview { flex: 1; }\n	panelview.cui-widget-panelview > vbox { flex: 1; min-height: 50vh; }\n	}\n";
    };
  };
}
