#!/usr/bin/env bash

echo "Checking if MariaDB is running..."

ps_output=$(ps aux | grep -i mysqld | grep -v grep)

if [ -n "$ps_output" ]
then
    echo "MariaDB is running. Here is the process information:"
    echo "$ps_output"
    echo "Attempting to connect to MariaDB..."
    echo "Please hit enter when prompted for a password (leave it blank)."
    mysql -h 127.0.0.1 -P 3306 -u root -p
else
    echo "MariaDB is not running. Remember to run 'devenv up' to start the Redis and MariaDB instance."
fi

